### PR TITLE
Rebuild the syntax with regions

### PR DESCRIPTION
**Pull request by michaelblyons**
Hi @mariozaizar. I learned some things since my first attempts in 2015-2017 at [michaelblyons/SublimeSyntax-Email](https://github.com/michaelblyons/SublimeSyntax-Email). I hope they are welcome here.

This PR:
- [x] Navigate to headers and body sections (<kbd>Cmd</kbd>+<kbd>R</kbd>).
    + This context awareness will also be helpful for future improvements.
- [x] Highlighting within headers.
- [x] Closer to suggested scope documentation.
- [x] Hover preview for Base64 text.
- [x] Hover preview for Base64 images.
- [x] Hovering over datetimes shows the timestamp in your local time and in UTC.
- [x] Highlight Base64 and Quoted-Printable __only__ if the header says to
    + Some exceptions apply.
- [x] Highlight HTML __only__ if the header says to
    + Some exceptions apply.
- [x] `prototype` Quoted Printable into HTML where appropriate.
- [x] Allowances for `Content-transfer-encoding` appearing before `Content-type`.
   + This is done for some cases but not all of them.

Maybe future:
- [ ] Regression tests.

### CODE REVIEW

**Comment by mariozaizar** [comment]
Thanks for your PR @michaelblyons ❤️, I will review this soon. 
Can you provide before/after screenshoots highlithing the new parts for reference. Thanks!

**Comment by michaelblyons** [comment]
I'll try to do that next 7 days or so. Wait for a few more pushes. This weekend, I found and fixed some small issues with a few emails I tried with. I also have some more improvements.

One of those is hover preview for Base64 text.

Screen Shot 2020-05-18 at 2 04 22 PM

Before you merge, I want to see if I can render attached base64 image data in the hover.

**Comment by michaelblyons** [comment]
Screen Shot 2020-06-13 at 11 16 41 PM

Image hovers work now, and a lot of the quoted-printable and base64 rules are now boxed into the context where they are expected.

Before:
Screen Shot 2020-06-14 at 1 13 38 AM

After:
Screen Shot 2020-06-14 at 1 17 04 AM

The text hover now shows HTML as well.
Screen Shot 2020-06-14 at 1 22 18 AM

**Comment by mariozaizar** [comment]
Wow, thanks for all of these! @michaelblyons 

Sorry for the waiting, it's been crazy at work and family. But I'm planning to get this reviewed and/or merged this weekend.

**Comment by michaelblyons** [comment]
Bump.

**Pull request merged**
